[2m2025-08-25T19:08:40.479583Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-25T19:08:40.479829Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'u:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-25T19:08:40.482137Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-25T19:08:41.054624Z[0m [[32m[1minfo     [0m] [1m[<main>] Initialized OpenAIService[0m
[2m2025-08-26T17:04:50.335965Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T17:04:50.336370Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T17:04:50.339420Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T17:04:51.327397Z[0m [[32m[1minfo     [0m] [1m[<main>] Initialized OpenAIService[0m
[2m2025-08-26T17:53:09.022045Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T17:53:09.022406Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T17:53:09.025224Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T17:53:09.458784Z[0m [[32m[1minfo     [0m] [1m[<main>] Initialized OpenAIService[0m
[2m2025-08-26T18:00:02.515498Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T18:00:02.515883Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T18:00:02.518736Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T18:00:19.245732Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-26T18:00:19.246110Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-26T18:00:19.246272Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-26T18:00:19.246439Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-26T18:00:19.246635Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-26T18:00:55.783219Z[0m [[31m[1merror    [0m] [1m[R4lkxVyrFoY::process][MessageEventComposer][CannedResponseGenerator] Generation failed: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing[0m
[2m2025-08-26T18:00:55.835402Z[0m [[31m[1merror    [0m] [1m[R4lkxVyrFoY::process][MessageEventComposer][CannedResponseGenerator] Preamble generation failed[0m
[2m2025-08-26T18:00:55.836550Z[0m [[31m[1merror    [0m] [1m[R4lkxVyrFoY::process][MessageEventComposer][CannedResponseGenerator] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 75, in generate
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:00:55.852945Z[0m [[31m[1merror    [0m] [1m[R4lkxVyrFoY::process] Processing context for session 8CsImV2ZCc failed[0m
[2m2025-08-26T18:00:55.854692Z[0m [[31m[1merror    [0m] [1m[R4lkxVyrFoY::process] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 173, in process
    await self._do_process(loaded_context)
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 274, in _do_process
    iteration_result = await self._run_preparation_iteration(context, preamble_task)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 454, in _run_preparation_iteration
    result = await self._run_initial_preparation_iteration(context, preamble_task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 556, in _run_initial_preparation_iteration
    if not await preamble_task:
           ^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 830, in preamble_task
    if await self._generate_preamble(context):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 861, in _generate_preamble
    for event_generation_result in await self._get_message_composer(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context.agent
        ^^^^^^^^^^^^^
    ).generate_preamble(context=context):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 75, in generate
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:00:55.856865Z[0m [[31m[1merror    [0m] [1m[R4lkxVyrFoY::process] Processing error: ['Traceback (most recent call last):\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 173, in process\n'
 '    await self._do_process(loaded_context)\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 274, in _do_process\n'
 '    iteration_result = await self._run_preparation_iteration(context, '
 'preamble_task)\n'
 '                       '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 454, in _run_preparation_iteration\n'
 '    result = await self._run_initial_preparation_iteration(context, '
 'preamble_task)\n'
 '             '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 556, in _run_initial_preparation_iteration\n'
 '    if not await preamble_task:\n'
 '           ^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 830, in preamble_task\n'
 '    if await self._generate_preamble(context):\n'
 '       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 861, in _generate_preamble\n'
 '    for event_generation_result in await self._get_message_composer(\n'
 '                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        context.agent\n'
 '        ^^^^^^^^^^^^^\n'
 '    ).generate_preamble(context=context):\n'
 '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 496, in generate_preamble\n'
 '    return await self._do_generate_preamble(context)\n'
 '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 639, in _do_generate_preamble\n'
 '    canrep = await self._canrep_fluid_preamble_generator.generate(\n'
 '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        prompt=prompt_builder, hints={"temperature": 0.1}\n'
 '        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 '  File "U:\\Parlant-Practice\\starter\\gemini_service.py", line 75, in '
 'generate\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\pydantic\\main.py", line 705, in '
 'model_validate\n'
 '    return cls.__pydantic_validator__.validate_python(\n'
 '           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n'
 '        obj, strict=strict, from_attributes=from_attributes, '
 'context=context, by_alias=by_alias, by_name=by_name\n'
 '        '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 'pydantic_core._pydantic_core.ValidationError: 1 validation error for '
 'CannedResponsePreambleSchema\n'
 'preamble\n'
 '  Field required [type=missing, input_value={}, input_type=dict]\n'
 '    For further information visit '
 'https://errors.pydantic.dev/2.11/v/missing\n'][0m
[2m2025-08-26T18:01:14.276223Z[0m [[33m[1mwarning  [0m] [1m[Rul7MMBOc56] HTTP Request: GET /sessions/8CsImV2ZCc/events cancelled after 18.405 seconds[0m
[2m2025-08-26T18:01:14.277092Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Cancelling all remaining tasks (2)[0m
[2m2025-08-26T18:01:14.280648Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Shutting down[0m
[2m2025-08-26T18:24:27.994704Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T18:24:27.994972Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T18:24:27.997716Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T18:24:34.192139Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-26T18:24:34.193542Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-26T18:24:34.194035Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-26T18:24:34.194535Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-26T18:24:34.194979Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-26T18:24:34.290789Z[0m [[32m[1minfo     [0m] [1m[RG0yvmPCiNR] Session not found (id='36bebTUVib')[0m
[2m2025-08-26T18:24:53.711254Z[0m [[31m[1merror    [0m] [1m[RoWyhQb9bmT::process][MessageEventComposer][CannedResponseGenerator] Generation failed: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing[0m
[2m2025-08-26T18:24:53.724403Z[0m [[31m[1merror    [0m] [1m[RoWyhQb9bmT::process][MessageEventComposer][CannedResponseGenerator] Preamble generation failed[0m
[2m2025-08-26T18:24:53.728472Z[0m [[31m[1merror    [0m] [1m[RoWyhQb9bmT::process][MessageEventComposer][CannedResponseGenerator] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 79, in generate
    model_instance = schema_type.model_validate({})
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:24:53.804143Z[0m [[31m[1merror    [0m] [1m[RoWyhQb9bmT::process] Processing context for session 13XPj2di0n failed[0m
[2m2025-08-26T18:24:53.807168Z[0m [[31m[1merror    [0m] [1m[RoWyhQb9bmT::process] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 173, in process
    await self._do_process(loaded_context)
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 274, in _do_process
    iteration_result = await self._run_preparation_iteration(context, preamble_task)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 454, in _run_preparation_iteration
    result = await self._run_initial_preparation_iteration(context, preamble_task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 556, in _run_initial_preparation_iteration
    if not await preamble_task:
           ^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 830, in preamble_task
    if await self._generate_preamble(context):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 861, in _generate_preamble
    for event_generation_result in await self._get_message_composer(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context.agent
        ^^^^^^^^^^^^^
    ).generate_preamble(context=context):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 79, in generate
    model_instance = schema_type.model_validate({})
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:24:53.810998Z[0m [[31m[1merror    [0m] [1m[RoWyhQb9bmT::process] Processing error: ['Traceback (most recent call last):\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 173, in process\n'
 '    await self._do_process(loaded_context)\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 274, in _do_process\n'
 '    iteration_result = await self._run_preparation_iteration(context, '
 'preamble_task)\n'
 '                       '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 454, in _run_preparation_iteration\n'
 '    result = await self._run_initial_preparation_iteration(context, '
 'preamble_task)\n'
 '             '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 556, in _run_initial_preparation_iteration\n'
 '    if not await preamble_task:\n'
 '           ^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 830, in preamble_task\n'
 '    if await self._generate_preamble(context):\n'
 '       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 861, in _generate_preamble\n'
 '    for event_generation_result in await self._get_message_composer(\n'
 '                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        context.agent\n'
 '        ^^^^^^^^^^^^^\n'
 '    ).generate_preamble(context=context):\n'
 '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 496, in generate_preamble\n'
 '    return await self._do_generate_preamble(context)\n'
 '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 639, in _do_generate_preamble\n'
 '    canrep = await self._canrep_fluid_preamble_generator.generate(\n'
 '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        prompt=prompt_builder, hints={"temperature": 0.1}\n'
 '        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 '  File "U:\\Parlant-Practice\\starter\\gemini_service.py", line 79, in '
 'generate\n'
 '    model_instance = schema_type.model_validate({})\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\pydantic\\main.py", line 705, in '
 'model_validate\n'
 '    return cls.__pydantic_validator__.validate_python(\n'
 '           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n'
 '        obj, strict=strict, from_attributes=from_attributes, '
 'context=context, by_alias=by_alias, by_name=by_name\n'
 '        '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 'pydantic_core._pydantic_core.ValidationError: 1 validation error for '
 'CannedResponsePreambleSchema\n'
 'preamble\n'
 '  Field required [type=missing, input_value={}, input_type=dict]\n'
 '    For further information visit '
 'https://errors.pydantic.dev/2.11/v/missing\n'][0m
[2m2025-08-26T18:25:33.896125Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T18:25:33.896484Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T18:25:33.899189Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T18:25:40.004689Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-26T18:25:40.005336Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-26T18:25:40.005573Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-26T18:25:40.005781Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-26T18:25:40.005964Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-26T18:25:40.287537Z[0m [[32m[1minfo     [0m] [1m[RnkKT3ubJ4o] Session not found (id='13XPj2di0n')[0m
[2m2025-08-26T18:25:54.678295Z[0m [[31m[1merror    [0m] [1m[RmbDdjds3RF::process][MessageEventComposer][CannedResponseGenerator] Generation failed: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing[0m
[2m2025-08-26T18:25:54.681771Z[0m [[31m[1merror    [0m] [1m[RmbDdjds3RF::process][MessageEventComposer][CannedResponseGenerator] Preamble generation failed[0m
[2m2025-08-26T18:25:54.683184Z[0m [[31m[1merror    [0m] [1m[RmbDdjds3RF::process][MessageEventComposer][CannedResponseGenerator] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 79, in generate
    model_instance = schema_type.model_validate({})
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:25:54.738287Z[0m [[31m[1merror    [0m] [1m[RmbDdjds3RF::process] Processing context for session xJOSzn1yCz failed[0m
[2m2025-08-26T18:25:54.740841Z[0m [[31m[1merror    [0m] [1m[RmbDdjds3RF::process] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 173, in process
    await self._do_process(loaded_context)
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 274, in _do_process
    iteration_result = await self._run_preparation_iteration(context, preamble_task)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 454, in _run_preparation_iteration
    result = await self._run_initial_preparation_iteration(context, preamble_task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 556, in _run_initial_preparation_iteration
    if not await preamble_task:
           ^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 830, in preamble_task
    if await self._generate_preamble(context):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 861, in _generate_preamble
    for event_generation_result in await self._get_message_composer(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context.agent
        ^^^^^^^^^^^^^
    ).generate_preamble(context=context):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 79, in generate
    model_instance = schema_type.model_validate({})
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:25:54.744145Z[0m [[31m[1merror    [0m] [1m[RmbDdjds3RF::process] Processing error: ['Traceback (most recent call last):\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 173, in process\n'
 '    await self._do_process(loaded_context)\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 274, in _do_process\n'
 '    iteration_result = await self._run_preparation_iteration(context, '
 'preamble_task)\n'
 '                       '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 454, in _run_preparation_iteration\n'
 '    result = await self._run_initial_preparation_iteration(context, '
 'preamble_task)\n'
 '             '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 556, in _run_initial_preparation_iteration\n'
 '    if not await preamble_task:\n'
 '           ^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 830, in preamble_task\n'
 '    if await self._generate_preamble(context):\n'
 '       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 861, in _generate_preamble\n'
 '    for event_generation_result in await self._get_message_composer(\n'
 '                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        context.agent\n'
 '        ^^^^^^^^^^^^^\n'
 '    ).generate_preamble(context=context):\n'
 '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 496, in generate_preamble\n'
 '    return await self._do_generate_preamble(context)\n'
 '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 639, in _do_generate_preamble\n'
 '    canrep = await self._canrep_fluid_preamble_generator.generate(\n'
 '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        prompt=prompt_builder, hints={"temperature": 0.1}\n'
 '        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 '  File "U:\\Parlant-Practice\\starter\\gemini_service.py", line 79, in '
 'generate\n'
 '    model_instance = schema_type.model_validate({})\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\pydantic\\main.py", line 705, in '
 'model_validate\n'
 '    return cls.__pydantic_validator__.validate_python(\n'
 '           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n'
 '        obj, strict=strict, from_attributes=from_attributes, '
 'context=context, by_alias=by_alias, by_name=by_name\n'
 '        '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 'pydantic_core._pydantic_core.ValidationError: 1 validation error for '
 'CannedResponsePreambleSchema\n'
 'preamble\n'
 '  Field required [type=missing, input_value={}, input_type=dict]\n'
 '    For further information visit '
 'https://errors.pydantic.dev/2.11/v/missing\n'][0m
[2m2025-08-26T18:26:48.948600Z[0m [[33m[1mwarning  [0m] [1m[RE1dlGcDhDz] HTTP Request: GET /sessions/xJOSzn1yCz/events cancelled after 54.105 seconds[0m
[2m2025-08-26T18:26:48.949728Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Cancelling all remaining tasks (2)[0m
[2m2025-08-26T18:26:48.953404Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Shutting down[0m
[2m2025-08-26T18:26:56.624792Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T18:26:56.625105Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T18:26:56.627368Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T18:27:02.699420Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-26T18:27:02.699966Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-26T18:27:02.700228Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-26T18:27:02.700399Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-26T18:27:02.700587Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-26T18:27:02.793083Z[0m [[32m[1minfo     [0m] [1m[RPkS97AHgSA] Session not found (id='xJOSzn1yCz')[0m
[2m2025-08-26T18:27:16.662790Z[0m [[31m[1merror    [0m] [1m[RjBW31fr5or::process][MessageEventComposer][CannedResponseGenerator] Generation failed: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing[0m
[2m2025-08-26T18:27:16.666022Z[0m [[31m[1merror    [0m] [1m[RjBW31fr5or::process][MessageEventComposer][CannedResponseGenerator] Preamble generation failed[0m
[2m2025-08-26T18:27:16.667067Z[0m [[31m[1merror    [0m] [1m[RjBW31fr5or::process][MessageEventComposer][CannedResponseGenerator] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 79, in generate
    model_instance = schema_type.model_validate({})
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:27:16.696775Z[0m [[31m[1merror    [0m] [1m[RjBW31fr5or::process] Processing context for session q47y4wBCi2 failed[0m
[2m2025-08-26T18:27:16.698641Z[0m [[31m[1merror    [0m] [1m[RjBW31fr5or::process] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 173, in process
    await self._do_process(loaded_context)
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 274, in _do_process
    iteration_result = await self._run_preparation_iteration(context, preamble_task)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 454, in _run_preparation_iteration
    result = await self._run_initial_preparation_iteration(context, preamble_task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 556, in _run_initial_preparation_iteration
    if not await preamble_task:
           ^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 830, in preamble_task
    if await self._generate_preamble(context):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 861, in _generate_preamble
    for event_generation_result in await self._get_message_composer(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context.agent
        ^^^^^^^^^^^^^
    ).generate_preamble(context=context):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 79, in generate
    model_instance = schema_type.model_validate({})
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:27:16.701065Z[0m [[31m[1merror    [0m] [1m[RjBW31fr5or::process] Processing error: ['Traceback (most recent call last):\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 173, in process\n'
 '    await self._do_process(loaded_context)\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 274, in _do_process\n'
 '    iteration_result = await self._run_preparation_iteration(context, '
 'preamble_task)\n'
 '                       '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 454, in _run_preparation_iteration\n'
 '    result = await self._run_initial_preparation_iteration(context, '
 'preamble_task)\n'
 '             '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 556, in _run_initial_preparation_iteration\n'
 '    if not await preamble_task:\n'
 '           ^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 830, in preamble_task\n'
 '    if await self._generate_preamble(context):\n'
 '       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 861, in _generate_preamble\n'
 '    for event_generation_result in await self._get_message_composer(\n'
 '                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        context.agent\n'
 '        ^^^^^^^^^^^^^\n'
 '    ).generate_preamble(context=context):\n'
 '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 496, in generate_preamble\n'
 '    return await self._do_generate_preamble(context)\n'
 '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 639, in _do_generate_preamble\n'
 '    canrep = await self._canrep_fluid_preamble_generator.generate(\n'
 '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        prompt=prompt_builder, hints={"temperature": 0.1}\n'
 '        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 '  File "U:\\Parlant-Practice\\starter\\gemini_service.py", line 79, in '
 'generate\n'
 '    model_instance = schema_type.model_validate({})\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\pydantic\\main.py", line 705, in '
 'model_validate\n'
 '    return cls.__pydantic_validator__.validate_python(\n'
 '           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n'
 '        obj, strict=strict, from_attributes=from_attributes, '
 'context=context, by_alias=by_alias, by_name=by_name\n'
 '        '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 'pydantic_core._pydantic_core.ValidationError: 1 validation error for '
 'CannedResponsePreambleSchema\n'
 'preamble\n'
 '  Field required [type=missing, input_value={}, input_type=dict]\n'
 '    For further information visit '
 'https://errors.pydantic.dev/2.11/v/missing\n'][0m
[2m2025-08-26T18:28:45.780252Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Cancelling all remaining tasks (2)[0m
[2m2025-08-26T18:28:45.782604Z[0m [[33m[1mwarning  [0m] [1m[R34xPCFr2CZ] HTTP Request: GET /sessions/q47y4wBCi2/events cancelled after 28.964 seconds[0m
[2m2025-08-26T18:28:45.784105Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Cancelling all remaining tasks (1)[0m
[2m2025-08-26T18:28:45.784374Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Shutting down[0m
[2m2025-08-26T18:29:08.301113Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T18:29:08.301755Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T18:29:08.307159Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T18:29:17.164309Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-26T18:29:17.164674Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-26T18:29:17.164872Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-26T18:29:17.165071Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-26T18:29:17.165298Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-26T18:29:45.743513Z[0m [[32m[1minfo     [0m] [1m[RFyNjvAWJOx::process] Processing context for session essvKtAtFO finished in 7.597 seconds[0m
[2m2025-08-26T18:30:03.715319Z[0m [[32m[1minfo     [0m] [1m[R6XKARGEJtF::process] Processing context for session essvKtAtFO finished in 7.6 seconds[0m
[2m2025-08-26T18:32:59.096935Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T18:32:59.097184Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T18:32:59.099277Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T18:33:05.043807Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-26T18:33:05.045514Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-26T18:33:05.046380Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-26T18:33:05.047263Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-26T18:33:05.048142Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-26T18:33:05.523930Z[0m [[32m[1minfo     [0m] [1m[RP34qTXlOHC] Session not found (id='essvKtAtFO')[0m
[2m2025-08-26T18:33:24.168367Z[0m [[32m[1minfo     [0m] [1m[Rm2rgkxEs4x::process] Processing context for session gcOcTKQMgk finished in 7.725 seconds[0m
[2m2025-08-26T18:35:36.789332Z[0m [[32m[1minfo     [0m] [1m[RTtimOhLXOl::process] Processing context for session gcOcTKQMgk finished in 7.324 seconds[0m
[2m2025-08-26T18:37:54.527435Z[0m [[33m[1mwarning  [0m] [1m[R0HXpRrqMuL] HTTP Request: GET /sessions/gcOcTKQMgk/events cancelled after 17.662 seconds[0m
[2m2025-08-26T18:37:54.528665Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Cancelling all remaining tasks (2)[0m
[2m2025-08-26T18:37:54.533501Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Shutting down[0m
[2m2025-08-26T18:38:02.893787Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T18:38:02.894083Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T18:38:02.896526Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T18:38:08.938836Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-26T18:38:08.939336Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-26T18:38:08.939565Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-26T18:38:08.939769Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-26T18:38:08.939980Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-26T18:38:09.159161Z[0m [[32m[1minfo     [0m] [1m[ROM6eLpn2xY] Session not found (id='gcOcTKQMgk')[0m
[2m2025-08-26T18:38:24.668748Z[0m [[31m[1merror    [0m] [1m[R8rrNJmKb0U::process][MessageEventComposer][CannedResponseGenerator] Generation failed: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing[0m
[2m2025-08-26T18:38:24.673247Z[0m [[31m[1merror    [0m] [1m[R8rrNJmKb0U::process][MessageEventComposer][CannedResponseGenerator] Preamble generation failed[0m
[2m2025-08-26T18:38:24.674583Z[0m [[31m[1merror    [0m] [1m[R8rrNJmKb0U::process][MessageEventComposer][CannedResponseGenerator] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 141, in generate
    model_instance = schema_type.model_validate({})
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:38:24.691165Z[0m [[31m[1merror    [0m] [1m[R8rrNJmKb0U::process] Processing context for session y0yRxNmpyr failed[0m
[2m2025-08-26T18:38:24.694111Z[0m [[31m[1merror    [0m] [1m[R8rrNJmKb0U::process] Traceback (most recent call last):
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 277, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\loggers.py", line 411, in operation
    yield
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 173, in process
    await self._do_process(loaded_context)
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 274, in _do_process
    iteration_result = await self._run_preparation_iteration(context, preamble_task)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 454, in _run_preparation_iteration
    result = await self._run_initial_preparation_iteration(context, preamble_task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 556, in _run_initial_preparation_iteration
    if not await preamble_task:
           ^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 830, in preamble_task
    if await self._generate_preamble(context):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\engine.py", line 861, in _generate_preamble
    for event_generation_result in await self._get_message_composer(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context.agent
        ^^^^^^^^^^^^^
    ).generate_preamble(context=context):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 496, in generate_preamble
    return await self._do_generate_preamble(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\Python313\Lib\site-packages\parlant\core\engines\alpha\canned_response_generator.py", line 639, in _do_generate_preamble
    canrep = await self._canrep_fluid_preamble_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prompt=prompt_builder, hints={"temperature": 0.1}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
   File "U:\Parlant-Practice\starter\gemini_service.py", line 141, in generate
    model_instance = schema_type.model_validate({})
   File "C:\Program Files\Python313\Lib\site-packages\pydantic\main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
 pydantic_core._pydantic_core.ValidationError: 1 validation error for CannedResponsePreambleSchema
preamble
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[0m
[2m2025-08-26T18:38:24.696897Z[0m [[31m[1merror    [0m] [1m[R8rrNJmKb0U::process] Processing error: ['Traceback (most recent call last):\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 173, in process\n'
 '    await self._do_process(loaded_context)\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 274, in _do_process\n'
 '    iteration_result = await self._run_preparation_iteration(context, '
 'preamble_task)\n'
 '                       '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 454, in _run_preparation_iteration\n'
 '    result = await self._run_initial_preparation_iteration(context, '
 'preamble_task)\n'
 '             '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 556, in _run_initial_preparation_iteration\n'
 '    if not await preamble_task:\n'
 '           ^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 830, in preamble_task\n'
 '    if await self._generate_preamble(context):\n'
 '       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\engine.py", '
 'line 861, in _generate_preamble\n'
 '    for event_generation_result in await self._get_message_composer(\n'
 '                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        context.agent\n'
 '        ^^^^^^^^^^^^^\n'
 '    ).generate_preamble(context=context):\n'
 '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 496, in generate_preamble\n'
 '    return await self._do_generate_preamble(context)\n'
 '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\parlant\\core\\engines\\alpha\\canned_response_generator.py", '
 'line 639, in _do_generate_preamble\n'
 '    canrep = await self._canrep_fluid_preamble_generator.generate(\n'
 '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '        prompt=prompt_builder, hints={"temperature": 0.1}\n'
 '        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 '  File "U:\\Parlant-Practice\\starter\\gemini_service.py", line 141, in '
 'generate\n'
 '    model_instance = schema_type.model_validate({})\n',
 '  File "C:\\Program '
 'Files\\Python313\\Lib\\site-packages\\pydantic\\main.py", line 705, in '
 'model_validate\n'
 '    return cls.__pydantic_validator__.validate_python(\n'
 '           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n'
 '        obj, strict=strict, from_attributes=from_attributes, '
 'context=context, by_alias=by_alias, by_name=by_name\n'
 '        '
 '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
 '    )\n'
 '    ^\n',
 'pydantic_core._pydantic_core.ValidationError: 1 validation error for '
 'CannedResponsePreambleSchema\n'
 'preamble\n'
 '  Field required [type=missing, input_value={}, input_type=dict]\n'
 '    For further information visit '
 'https://errors.pydantic.dev/2.11/v/missing\n'][0m
[2m2025-08-26T18:39:21.803314Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Cancelling all remaining tasks (2)[0m
[2m2025-08-26T18:39:21.804057Z[0m [[33m[1mwarning  [0m] [1m[RXqkeJ5vJ5y] HTTP Request: GET /sessions/y0yRxNmpyr/events cancelled after 56.843 seconds[0m
[2m2025-08-26T18:39:21.804705Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Cancelling all remaining tasks (1)[0m
[2m2025-08-26T18:39:21.805059Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Shutting down[0m
[2m2025-08-26T18:39:29.028100Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-26T18:39:29.028387Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-26T18:39:29.030307Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-26T18:39:34.962054Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-26T18:39:34.963822Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-26T18:39:34.964777Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-26T18:39:34.965634Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-26T18:39:34.966444Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-26T18:39:35.130372Z[0m [[32m[1minfo     [0m] [1m[RZ5WLoU90qd] Session not found (id='y0yRxNmpyr')[0m
[2m2025-08-26T18:39:50.879801Z[0m [[32m[1minfo     [0m] [1m[RHwvBr4Sp8c::process] Processing context for session gFtyTnYzBa finished in 8.072 seconds[0m
[2m2025-08-27T17:25:14.615507Z[0m [[32m[1minfo     [0m] [1m[<main>] Parlant server version 3.0.1[0m
[2m2025-08-27T17:25:14.616527Z[0m [[32m[1minfo     [0m] [1m[<main>] Using home directory 'U:\Parlant-Practice\starter\parlant-data'[0m
[2m2025-08-27T17:25:14.623041Z[0m [[32m[1minfo     [0m] [1m[<main>] No external modules selected[0m
[2m2025-08-27T17:25:22.358164Z[0m [[32m[1minfo     [0m] [1m[<main>] .-----------------------------------------.[0m
[2m2025-08-27T17:25:22.362519Z[0m [[32m[1minfo     [0m] [1m[<main>] | Server is ready for some serious action |[0m
[2m2025-08-27T17:25:22.366657Z[0m [[32m[1minfo     [0m] [1m[<main>] '-----------------------------------------'[0m
[2m2025-08-27T17:25:22.369454Z[0m [[32m[1minfo     [0m] [1m[<main>] Server authorization policy: development[0m
[2m2025-08-27T17:25:22.372538Z[0m [[32m[1minfo     [0m] [1m[<main>] Try the Sandbox UI at http://localhost:8800[0m
[2m2025-08-27T17:25:45.495096Z[0m [[32m[1minfo     [0m] [1m[RKh3OHC7Jtr::process] Processing context for session 8RdkVRDI9D finished in 7.533 seconds[0m
[2m2025-08-27T17:26:08.057475Z[0m [[32m[1minfo     [0m] [1m[REU0zGFrVB3::process] Processing context for session 8RdkVRDI9D finished in 7.77 seconds[0m
[2m2025-08-27T17:45:59.535940Z[0m [[32m[1minfo     [0m] [1m[R8p5gRelPIs::process] Processing context for session 8RdkVRDI9D finished in 11.023 seconds[0m
[2m2025-08-27T17:46:34.144252Z[0m [[32m[1minfo     [0m] [1m[RPlTMjlyGSY::process] Processing context for session 8RdkVRDI9D finished in 6.112 seconds[0m
[2m2025-08-27T17:46:53.193761Z[0m [[32m[1minfo     [0m] [1m[RozXQgwJZQO::process] Processing context for session 8RdkVRDI9D finished in 7.956 seconds[0m
[2m2025-08-27T17:47:37.535477Z[0m [[32m[1minfo     [0m] [1m[RFSeMnxDO25::process] Processing context for session 8RdkVRDI9D finished in 12.992 seconds[0m
[2m2025-08-27T17:49:13.688515Z[0m [[32m[1minfo     [0m] [1m[ReCcm7uBgZp::process] Processing context for session 8RdkVRDI9D finished in 11.466 seconds[0m
[2m2025-08-27T17:50:49.638859Z[0m [[32m[1minfo     [0m] [1m[RN3xJyW62dk::process] Processing context for session 8RdkVRDI9D finished in 11.198 seconds[0m
[2m2025-08-27T18:35:12.167635Z[0m [[33m[1mwarning  [0m] [1m[REY4eXnq0Zf] HTTP Request: GET /sessions/8RdkVRDI9D/events cancelled after 21.138 seconds[0m
[2m2025-08-27T18:35:12.172230Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Cancelling all remaining tasks (2)[0m
[2m2025-08-27T18:35:12.190171Z[0m [[32m[1minfo     [0m] [1m[<main>] BackgroundTaskService: Shutting down[0m
